name: env
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyter
  - numpy
  - scipy
  - pandas
  - Pillow
  - matplotlib
  - seaborn
  - plotly::plotly
  - scikit-learn
  - moviepy
  - pytorch=1.4.0
  - cudatoolkit=10.1
  - torchmetrics
  - pip
  - pip:
    - torchvision==0.5.0
    - autoroot
    - autorootcwd
    - wandb