# path to root directory
root_dir: ${oc.env:PROJECT_ROOT}

# path to data directory
data_dir: ${paths.root_dir}/data/

# path to logging directory
log_dir: ${paths.root_dir}/logs/

# path to output directory
output_dir: ${paths.root_dir}/runs/model=${tags[0]},dataset=${tags[1]},loss=${tags[2]},seed=${seed}/${now:%Y-%m-%d}T${now:%H-%M-%S}/${job_name}
