defaults:
  - _self_
  - transforms: normalize

_target_: src.data.datamodules.SameDifferentShapeDataModule

root: ${paths.data_dir}

data_dir: "same-different-shape-depth-pairs/curriculum-learning/v40"

train_batch_size: 16

test_batch_size: 128

num_workers: 0

pin_memory: False

seed: ${seed}